### ISSUE TITLE
ads too small/ look stupid in articles

### ISSUE THREAD

**Issue by SonjaKT** [sfyimby/sfyimby#10]
maybe instead of appearing centered in between articles, they should be right justified and allow the article text to flow around them?

**Comment by bufordsharkley** [comment]
There may be a better ad solution than the "between the paragraphs" thing we have now.

If it were just desktop, having it be off to the side, and letting the article flow, would be very good. But the in-between-the-paragraphs works on mobile, and I'm seeing a good solution for accommodating both... (that said, there's a lot about good CSS that I don't know)
