### ISSUE TITLE
image sizing in the articles 

### ISSUE THREAD

**Issue by SonjaKT** [sfyimby/sfyimby#11]
They're too big in the articles.

**Comment by daguilarc** [comment]
yeah look at how this looks: http://sfbamo.com/news/over-three-months-prop-c-has-reduced-production-of-affordable-housing/

the charts are HUUUUUUUUUUGE and the cover picture is tiny. should be the other way around! (though the cover picture shouldn't be as fucking ginormous as the others currently are)

**Comment by ErikGoldman** [comment]
good catch. I have that fixed locally.
