### ISSUE TITLE
Footnotes occur at end of text flowblock, not end of page

### ISSUE THREAD

**Issue by bufordsharkley** [sfyimby/sfyimby#15]
Meaning that if you have a footnote in a middle-block, it could look like: 

![image](https://cloud.githubusercontent.com/assets/4923417/18456921/a4f137ea-7909-11e6-906b-5c4fe6bbaf53.png)

I'm not sure if there's a way to make "proper" footnotes work with text flowblocks.

**Comment by ErikGoldman** [comment]
looks like this got fixed! it wasn't me, but I'll close it out 😄
