### ISSUE TITLE
big ass gap at bottom of front page

### ISSUE THREAD

**Issue by SonjaKT** [sfyimby/sfyimby#17]
scroll down to the bottom of the front page, big ass gap between bottom of the page & button to go to the next page!!

**Comment by ErikGoldman** [comment]
hmm, I'm not sure if I see that. can you send a screenshot?

it looks like this to me: 
![screenshot 2016-09-14 11 26 09](https://cloud.githubusercontent.com/assets/243490/18524676/3e633bfc-7a6e-11e6-93e1-fe3ee536f766.png)

**Comment by ErikGoldman** [comment]
is this still an issue? I can't see it on sfbamo.com on either mobile or desktop

**Comment by daguilarc** [comment]
never was an issue on mobile but it's still an issue on desktop for me

**Comment by bufordsharkley** [comment]
Could you print-screen what you see and copy it into the issue on Github?

**Comment by daguilarc** [comment]
Omg sorry I had this confused with the big ass gap at the top of the page.
Totally thought this was the other thread. Bottom looks fine!

**Comment by ErikGoldman** [comment]
np 😄
